![Logo](Technikklein.png)

# Task 3: Python Data Science (Part 2)
### Data Science


##### Dozent: Prof. Dr. Stefan Edlich
##### Medieninformatik
##### Hochschule Emden/Leer
##### Sommersemester 2021
   
_____




The second task for this week was to work through the first 25 of the [101 Numpy Exercises](https://www.machinelearningplus.com/python/101-numpy-exercises-python/) and prove it by giving some 'sloppy' solves. :)

### Ex. 1 Load the countries.csv directly via URL import into your panda data frame!

In [1]:
import numpy as np
print(np.__version__)

1.20.1


### Ex. 2 Create a 1D array of numbers from 0 to 9.

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Ex. 3 Create a 3×3 numpy array of all True’s.

In [4]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Ex. 4 Extract all odd numbers from `arr`.

In [5]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

### Ex. 5 Replace all odd numbers in `arr` with -1.

In [10]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Ex. 6 Replace all odd numbers in `arr` with -1 without changing `arr`.

In [15]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)

print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Ex. 7 Convert a 1D array to a 2D array with 2 rows.

In [26]:
out.reshape(2, -1)

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

### Ex. 8 Stack the arrays `a` and `b` vertically.

In [38]:
a = np.arange(10).reshape(2, -1)
b = np.arange(10).reshape(2, -1)

c = np.concatenate([a, b], axis=0)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Ex. 9 Stack the arrays `a` and `b` horizontally.

In [42]:
d = np.concatenate([a, b], axis=-1)
d

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

### Ex. 10 Create the following pattern without hardcoding. Use only numpy functions and the below input array `a`.
Input: `a = np.array([1,2,3])`

Desired output: `#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`

(There is an easier solution, I saw it.)

In [51]:
a = np.array([1, 2, 3])
b = np.repeat(a, 3)
c = np.concatenate([a, a, a], axis=0)
d = np.concatenate([b, c], axis=0)
d

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### Ex. 11 Get the common items between `a` and `b`.
Input:

`a = np.array([1,2,3,2,3,4,3,4,5,6])`

`b = np.array([7,2,10,2,7,4,9,4,9,8])`

In [53]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a, b)
c

array([2, 4])

### Ex. 12 From array `a` remove all items present in array `b`.

In [54]:
d = np.setdiff1d(a,b)
d

array([1, 3, 5, 6])

### Ex. 13 Get the positions where elements of `a` and `b` match.

In [56]:
e = np.where(a == b)
e

(array([1, 3, 5, 7], dtype=int64),)

### Ex. 14 Get all items between 5 and 10 from `a`.

In [66]:
a = np.arange(10)
arr[(5 < a) & (a < 10)]

array([6, 7, 8, 9])

### Ex. 15 Convert the function `maxx` that works on two scalars, to work on two arrays.
Input:
```
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
```
(My result is prettier. :( )

In [101]:
def maxx(a, b):
    r = np.array([])
    for i in np.nditer(a):
        if a[i] > b[i]:
            r = np.append(r, np.array([a[i]]))
        else:
            r = np.append(r, np.array([b[i]]))
    return r
        
a = np.arange(10)
b = [10, 9 , 8, 7, 6, 5, 4, 3, 2, 1]
maxx(a, b)

array([10.,  9.,  8.,  7.,  6.,  5.,  6.,  7.,  8.,  9.])

### Ex. 16 Swap columns 1 and 2 in the array `arr`.
```
arr = np.arange(9).reshape(3,3)
arr
```

In [118]:
arr = np.arange(9).reshape(3,3)
print(arr)

arr = arr[:, [1,0,2]]
arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### Ex. 17 Swap rows 1 and 2 in the array `arr`.

In [119]:
arr = arr[[1,0,2], :]
arr

array([[4, 3, 5],
       [1, 0, 2],
       [7, 6, 8]])

### Ex. 18  Reverse the rows of a 2D array `arr`.

In [120]:
arr = arr[::-1]
arr

array([[7, 6, 8],
       [1, 0, 2],
       [4, 3, 5]])

### Ex. 19 Reverse the columns of a 2D array `arr`.

In [123]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:, ::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### Ex. 20 Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [127]:
a = np.random.uniform(5,10, size=(5,3))
a

array([[5.25172916, 7.17522825, 7.24465269],
       [7.5117384 , 7.84807767, 6.42229007],
       [5.56659765, 7.06706078, 6.22468044],
       [8.27475451, 5.38780709, 7.45379169],
       [6.57762072, 6.59860359, 7.48405169]])

### Ex. 21 Print or show only 3 decimal places of the numpy array `a`.

In [128]:
np.set_printoptions(precision=3)
a[:4]

array([[5.252, 7.175, 7.245],
       [7.512, 7.848, 6.422],
       [5.567, 7.067, 6.225],
       [8.275, 5.388, 7.454]])

### Ex. 22 Pretty print `rand_arr` by suppressing the scientific notation (like 1e10).
Input:
```
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
```

In [136]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

np.set_printoptions(suppress=True, precision=9)
rand_arr

array([[0.000543405, 0.000278369, 0.000424518],
       [0.000844776, 0.000004719, 0.000121569],
       [0.000670749, 0.000825853, 0.000136707]])

### Ex. 23 Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [137]:
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

### Ex. 24 Print the full numpy array `a` without truncating.

In [138]:
np.set_printoptions(threshold=15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Ex. 25 Import the [iris dataset](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data) keeping the text intact.

In [139]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
data = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

data[:3]


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)